### ISSUE TITLE
local_setup: import error

### ISSUE THREAD

**Issue by EgonFrerich** [feinheit/feincms-in-a-box#44]
After a fresh installation I have got this traceback:

(umg_dj) egon@xfEinzel ~/Entw/umg_dj/feincms-in-a-box/build/vankin_de $ fab local.setup
Traceback (most recent call last):
  File "/home/egon/Entw/umg_dj/bin/fab", line 9, in <module>
    load_entry_point('Fabric==1.10.2', 'console_scripts', 'fab')()
  File "/home/egon/Entw/umg_dj/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/egon/Entw/umg_dj/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/egon/Entw/umg_dj/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/egon/Entw/umg_dj/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/egon/Entw/umg_dj/lib/python3.4/site-packages/fabric/main.py", line 12, in <module>
    from operator import isMappingType
ImportError: cannot import name 'isMappingType'

**Comment by matthiask** [comment]
Thank you for the report!

Fabric does not support Python 3. You should not install fabric inside a Python 3-using virtualenv. 

This particular error has nothing to do with FeinCMS-in-a-box.
